CREATE TABLE IF NOT EXISTS rooms (
  code TEXT PRIMARY KEY,
  host_name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'LOBBY',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS matches (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  room_code TEXT NOT NULL,
  winner_name TEXT,
  total_rounds INTEGER NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  finished_at DATETIME
);

CREATE TABLE IF NOT EXISTS player_stats (
  name TEXT PRIMARY KEY,
  games_played INTEGER DEFAULT 0,
  wins INTEGER DEFAULT 0,
  last_played_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
